# Generated by Django 4.0.4 on 2022-09-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='ConfirmationCode',
            field=models.CharField(default='89965', max_length=10),
        ),
    ]
