# Generated by Django 4.1.1 on 2022-09-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_signup_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='ConfirmPassword',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='signup',
            name='Password',
            field=models.CharField(max_length=256),
        ),
    ]
