# Generated by Django 4.1.1 on 2022-09-29 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_signup_confirmpassword_alter_signup_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=20)),
                ('LastName', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=35, unique=True)),
                ('UserName', models.CharField(max_length=20, unique=True)),
                ('PhoneNumber', models.CharField(max_length=20)),
            ],
        ),
    ]
